AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
